### ISSUE TITLE
Documentation Link

### ISSUE THREAD

**Issue by bymayo** [intoeetive/protectedlinks#1]
The URL for the Documentation in the plugin store doesn't work, it links to:

https://github.com/intoeetive/protected-links/blob/master/README.md

**Comment by admench** [comment]
https://github.com/intoeetive/protectedlinks/blob/master/README.md

**Comment by bymayo** [comment]
I can get to the readme fine 👍 Just wanted to let you know that the readme when linked from the Craft 3 plugin was incorrect:

https://github.com/intoeetive/protectedlinks/blob/4c9b84c5f0787cdb7d42ecd787099ea145e43377/composer.json#L14

(And so are other URL's in there)

**Comment by intoeetive** [comment]
thanks @bymayo - released a fix
