### ISSUE TITLE
Allow everyone to download the asset

### ISSUE THREAD

**Issue by stijnelskens** [intoeetive/protectedlinks#12]
Hi there

Is it possible to allow everyone to download the assets or put it back to public.
I tried requireLogin: false but that doesnt seem to work..
Just like to use the download counter and not the protection.

Thanks in advance!

**Comment by intoeetive** [comment]
You can just omit all parameters and that would skip all kind of protection

**Comment by stijnelskens** [comment]
Ok yeah it works thanks!
