### ISSUE TITLE
is is possible to image-resize protected assets

### ISSUE THREAD

**Issue by hiasl** [intoeetive/protectedlinks#14]
Hi,
short question: is is possible to image-resize protected assets?
Thanks,
Matthias

**Comment by intoeetive** [comment]
If you speak about image manipulations that can be defined in CP then yes - the protection is taking place when you try to access the file using Twig template tag.
However Protected Links does not provide any way to access the scaled version, just the original, as it's solely based on Asset ID

**Comment by hiasl** [comment]
Thanks!
