### ISSUE TITLE
Error trying to install from Craft

### ISSUE THREAD

**Issue by panosdigital** [intoeetive/protectedlinks#4]
When I select to "install" the plugin from Craft, I get the following error:
`yii\base\ErrorException: Trying to get property of non-object`

**Comment by intoeetive** [comment]
@baronetto can you please enable dev mode in Craft and post detailed error message (specifically, what file and line is causing the error)

**Comment by panosdigital** [comment]
Dev mode is enabled by no additional information is output other than what I sent. For some reason "Protected Links" appears twice in the list of plugins.
ScreenShot:

<img width="1051" alt="screen shot 2018-08-20 at 15 35 46" src="https://user-images.githubusercontent.com/8502160/44341033-6bc2b080-a48f-11e8-997a-751837a9bcf2.png">

The error is produced when I tap to install the second. 

Also in the composer.json file the plugin appears as:
`"intoeetive/protected-links": "0.0.1-RC2"`

Should it be `protectedlinks` without the dash?

**Comment by intoeetive** [comment]
It looks like somehow you also got the plugin installed with 'dashed' name. Remove the line that says `"intoeetive/protected-links": "0.0.1-RC2"` then run `composer update` and you should be fine

**Comment by panosdigital** [comment]
That's definitely something I could have done. :) I removed everything and re-installed and it seems to be working fine. Thank you for your help.
