### ISSUE TITLE
User is not permitted to perform this action

### ISSUE THREAD

**Issue by bymayo** [intoeetive/protectedlinks#5]
I've hit a bit of an issue with the plugin, whenever a non-admin user tries to download a file they get the following error.

``` 
Unauthorised
User is not permitted to perform this action
```

Initially I thought it was because I was missing the `memberGroups` option, so I added this:

```
{% set link = craft.protectedLinks.link(
   {
      assetId: attributes.download.id,
      denyHotlink: true,
      requireLogin: false,
      dateExpires: now|date_modify('+1 day')|date('c'),
      memberGroups: [1,3]
   }
) %} 
```

But this still seems to cause the same error.

Another error also occured after adding `memberGroups`, which meant admin users that weren't in a member group could no longer also download the files.

So ideally, it would be good if `memberGroups` was defined, that it still allowed admins regardless (OR, theres another option to turn this on/off)

But my main issue is that no user, other than admins, can download anything.

**Comment by intoeetive** [comment]
In addition to its own checks, Protected Links is also checking whether the user has 'viewVolume' permission on the assets storage for the file that he's accessing. The error you see it becauses your users don't have access at that level

**Comment by bymayo** [comment]
@intoeetive That makes perfect sense! But, do you reckon it's worth mentioning this in the docs?

**Comment by intoeetive** [comment]
Good catch - added that to docs and allowed admins to download file even if group/member restriction is set

**Comment by bymayo** [comment]
Ace! Thanks - That works now :)

**Comment by sjcallender** [comment]
> In addition to its own checks, Protected Links is also checking whether the user has 'viewVolume' permission on the assets storage for the file that he's accessing. The error you see it becauses your users don't have access at that level

@intoeetive Can you add this to the docs? We ran into the same problem and were stumped and almost went with a different solution.

**Comment by sjcallender** [comment]
Oh, I see it now. Let me change my request then.

Can you **_highlight_** that note in the docs? :)
