### ISSUE TITLE
User is not permitted to perform this action

### ISSUE THREAD

**Issue by blocksera** [intoeetive/protectedlinks#9]
We're trying to create a way to just obfuscate the links but receiving this error when accessed without login. Did a little digging and found out that guest (non-logged in) users has no viewVolume permission. Have already tried requireLogin but its not working. How can we resolve it?

**Comment by proimage** [comment]
I'm getting the same issue here. Would love a resolution...

**Comment by blocksera** [comment]
Got to work by forking the repo and removing this line from `src/controllers/LinkController.php`.

```php
$this->_requirePermissionByAsset('viewVolume', $asset);
```

Obviously this allows downloads without authentication which is perfect for our case: obfuscating download links.

**Comment by iapparatus** [comment]
@intoeetive Will you consider making this line conditional on wheather the user is logged in or not? Sometimes all we want is to hide the location of the file and prevent hotlinking.

**Comment by jeroenlammerts** [comment]
@intoeetive ran into the same issue. You have a paid plugin, can we expect a bit more support? Or is this plugin not maintained anymore?

**Comment by intoeetive** [comment]
I am sorry for making everyone wait for so long.

The update has been released with a fix - now asset permissions are only checked if membership is required in any form.
